name: FirstRun

on: 
  workflow_dispatch:  # A button in Action page to start it
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
  watch:
    types: [started]
   
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id  # Click on STAR of your own to start it
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install requirements
      run: |
        pip install -r requirements.txt
    - name: Checkout branch
      run: |
        git checkout -b Demo
        echo $(cat /proc/sys/kernel/random/uuid) > UUID.txt
        git add .
        git config --global user.name "CSGO-Demo-Downloader"
        git config --global user.email "CSGO-Demo-Downloader@demodl.org"
        git commit -m "Create Demo Branch"
    - name: 'GitHub Push'
      if: steps.commit.output.status != 'success'
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: Demo